### ISSUE TITLE
RE: `--from-reference` doesn't seem to work in GitHub Actions

### ISSUE THREAD

**Issue by DeveloperC286** [mobusoperandi/michie#225]
I responded to the issue that was opened by a maintainer/contributor of this tool.

https://gitlab.com/DeveloperC/conventional_commits_linter/-/issues/1

I know GitLab is terrible with notifications so just prompting here, feel free to close this issue and the one on GitLab if you are satisfied.

**Comment by mightyiam** [comment]
I commented there. By the way, when trying to make sure that notifications are turned on for me on that GitLab issue, I looked at the switch for notifications and it was disabled and under it the text "Disabled by project owner", as if notifications across this project are disabled for all participants of this project, by the owner. My best guess. Although that would be a strange feature, wouldn't it...
